services:
  dev:
    image: cl00e9ment/node.js-builder
    restart: always
    container_name: ava-pro-dev
    command: [sh, -c, 'su node -c "pnpm install && pnpm run dev"']
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 1234:1234

  build:
    image: cl00e9ment/node.js-builder
    container_name: ava-pro-build
    command: [sh, -c, 'su node -c "pnpm install && pnpm run build"']
    volumes:
      - .:/code
    working_dir: /code
