name: Node CI/CD - devbuilds

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn ext:build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          retention-days: 3
          path: |
            dist/*.zip
            dist/*.xpi
